#***************************************
#SELENIUM OPERA NODE
#***************************************
apiVersion: v1
kind: Service
metadata:
  name: selenium-opera-node
  labels:
    name: selenium-opera-node
    component: "selenium-grid-4"
spec:
  selector:
    app: selenium-opera-node
  ports:
    - name: port1
      protocol: TCP
      port: 6900
      targetPort: 5900

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-opera-node-deployment
  labels:
    app: selenium-opera-node
    name: selenium-opera-node
    component: "selenium-grid-4"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-opera-node
  template:
    metadata:
      labels:
        app: selenium-opera-node
        name: selenium-opera-node
        component: "selenium-grid-4"
    spec:
      containers:
        - name: selenium-opera-node
          image: selenium/node-opera:4.0.0
          env:
            - name: SE_NODE_MAX_SESSIONS
              value: "5"
            - name: SE_EVENT_BUS_HOST
              value: "selenium-event-bus"
            - name: SE_EVENT_BUS_PUBLISH_PORT
              value: "4442"
            - name: SE_EVENT_BUS_SUBSCRIBE_PORT
              value: "4443"
          ports:
            - containerPort: 5553
              protocol: TCP
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
          resources:
            requests:
              memory: "1Gi"
              cpu: "1"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: dshm
          emptyDir: { "medium": "Memory" }